// =====================================================
// English-specific orchestration around the shared InnerTube primitives:
// list tracks → select the best English one (trackSelection.ts) → fetch its
// original baseUrl (no `tlang` — this is the English path, not translation)
// → parse → package into a TranscriptProviderResult. This is the fallback
// reached when the youtube-transcript package fails in a fallback-eligible
// way (see orchestrator.ts's matrix) — it reuses the exact request/parsing
// approach already proven by youtubeTranslatedCaptions.ts, via the shared
// innerTubeClient/parseTimedText modules.
// =====================================================

import { fetchCaptionTracks, fetchTimedText } from "./innerTubeClient";
import { selectEnglishTrack } from "./trackSelection";
import { parseTimedTextXml } from "./parseTimedText";
import { validateHttpPayload } from "./validation";
import { TranscriptFetchError, toTranscriptFetchError } from "./errors";
import type { TranscriptProviderResult } from "./types";

function isAbortError(err: unknown): boolean {
  return err instanceof Error && err.name === "AbortError";
}

export async function fetchViaInnerTube(videoId: string): Promise<TranscriptProviderResult> {
  const startedAt = Date.now();

  const { tracks, diagnostics } = await fetchCaptionTracks(videoId).catch((err) => {
    throw toTranscriptFetchError(err, isAbortError(err) ? "TIMEOUT" : "NETWORK_ERROR");
  });

  if (diagnostics.httpStatus === 429) {
    throw new TranscriptFetchError("YOUTUBE_RATE_LIMITED", "InnerTube returned HTTP 429.", {
      safeContext: { httpStatus: diagnostics.httpStatus },
    });
  }
  if (diagnostics.httpStatus >= 500) {
    throw new TranscriptFetchError("NETWORK_ERROR", "InnerTube returned a server error.", {
      safeContext: { httpStatus: diagnostics.httpStatus },
    });
  }

  if (!tracks || tracks.length === 0) {
    throw new TranscriptFetchError("CAPTIONS_DISABLED", "No caption tracks found via InnerTube.", {
      safeContext: {
        httpStatus: diagnostics.httpStatus,
        playabilityStatus: diagnostics.playabilityStatus,
      },
    });
  }

  const selection = selectEnglishTrack(tracks);
  if (!selection) {
    throw new TranscriptFetchError("LANGUAGE_NOT_FOUND", "No English caption track found via InnerTube.", {
      safeContext: { trackCount: tracks.length },
    });
  }

  console.log(
    `[innerTubeProvider] videoId=${videoId} selectedTrack languageCode=${selection.track.languageCode} ` +
      `kind=${selection.track.kind ?? "manual"} reason=${selection.reason}`
  );

  const httpResult = await fetchTimedText(selection.track.baseUrl).catch((err) => {
    throw toTranscriptFetchError(err, isAbortError(err) ? "TIMEOUT" : "NETWORK_ERROR");
  });

  const payloadCheck = validateHttpPayload(httpResult);
  if (!payloadCheck.ok) {
    throw new TranscriptFetchError(payloadCheck.failure.code, payloadCheck.failure.message, {
      safeContext: payloadCheck.failure.safeContext,
    });
  }

  const cues = parseTimedTextXml(httpResult.text);
  if (cues.length === 0) {
    throw new TranscriptFetchError("PARSER_ERROR", "Timed-text payload could not be parsed into cues.", {
      safeContext: { contentType: httpResult.contentType ?? undefined, byteLength: httpResult.text.length },
    });
  }

  return {
    provider: "innertube-raw",
    languageCode: selection.track.languageCode,
    isAutoGenerated: selection.track.kind === "asr",
    cues,
    diagnostics: { attemptCount: 1, durationMs: Date.now() - startedAt, trackKind: selection.track.kind },
  };
}
