// =====================================================
// Shared types for the YouTube caption-provider subsystem.
// See src/lib/youtubeCaptions/orchestrator.ts for how these compose.
// =====================================================

/** A single caption cue, normalized to unambiguous seconds (never ms). */
export interface CaptionCue {
  text: string;
  startSeconds: number;
  durationSeconds: number;
}

export type TranscriptProviderName =
  | "youtube-transcript"
  | "innertube-raw"
  | "manual"
  | "srt"
  | "vtt";

export interface TranscriptProviderDiagnostics {
  attemptCount: number;
  durationMs: number;
  trackKind?: string;
}

export interface TranscriptProviderResult {
  provider: TranscriptProviderName;
  languageCode: string;
  isAutoGenerated?: boolean;
  cues: CaptionCue[];
  diagnostics: TranscriptProviderDiagnostics;
}

/** Raw caption-track metadata as returned by YouTube's InnerTube player endpoint. */
export interface CaptionTrackMeta {
  baseUrl: string;
  languageCode: string;
  /** "asr" for auto-generated tracks; absent/other for manually authored ones. */
  kind?: string;
  /** e.g. "a.en", ".en" — sometimes carries more precise language/authorship signal than languageCode. */
  vssId?: string;
  /** Human-readable display name, e.g. "English (auto-generated)". Never used alone to decide language. */
  name?: string;
  /** True when this track is itself YouTube's own translation of another track. */
  isTranslatable?: boolean;
}

export interface TrackSelectionResult {
  track: CaptionTrackMeta;
  /** Short machine-readable reason the track won, for safe (non-content) diagnostic logging. */
  reason: string;
}
