"use client";

/**
 * Learning Reports P5 — client state for the report page's AI actions.
 *
 * - Only explicit user actions POST (generate / explain / re-explain / save).
 *   Opening the report, a fingerprint change or a version change never does.
 * - Generated-but-unsaved output is shown as "Not saved yet", kept in
 *   sessionStorage (scoped by account, round and operation), retried ONCE
 *   automatically, and offered with an explicit Save.
 * - Polling while a generation runs only re-reads the report (GET), bounded
 *   and cancelled on unmount; it never re-posts generation.
 * - The hook is mounted per (account, round) — the page keys it so — and every
 *   response is also checked against the scope it was sent for.
 */
import { useCallback, useEffect, useRef, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { roundReportKeys } from "@/lib/queries/roundReport";
import { loadPending, recoveryKey, removePending, savePending, type PendingRecovery } from "@/lib/ai/recoveryStore";
import type { AiActionResponse, AiRecoverResponse, AiRecoveryEntry, UnsavedNoteView } from "@/lib/ai/types";

const POLL_MS = 3000;
const POLL_MAX = 20;
const AUTO_RETRY_DELAY_MS = 1500;

export interface QuotaView {
  configured: boolean;
  rpdUsed: number;
  rpdLimit: number;
  userRpdUsed?: number;
  userRpdLimit?: number;
  resetsAt: string;
}

export interface AiMessage {
  tone: "info" | "warn" | "error";
  text: string;
}

export function describeAction(r: AiActionResponse): AiMessage[] {
  const out: AiMessage[] = [];
  const o = r.overview.status;
  if (o === "saved") out.push({ tone: "info", text: "New assessment saved." });
  else if (o === "reused") out.push({ tone: "info", text: "Your saved assessment already matches your current answers — no AI request was used." });
  else if (o === "unusable") out.push({ tone: "warn", text: "The AI response had no usable overview, so your earlier assessment was kept." });
  else if (o === "superseded") out.push({ tone: "warn", text: "A newer assessment was started meanwhile; this result was discarded." });
  else if (o === "conflict" || o === "rejected") out.push({ tone: "warn", text: "This assessment couldn't be stored (a different result is already saved, or the app is outdated — reload the page)." });
  else if (o === "not_saved") out.push({ tone: "warn", text: "The new assessment is shown but not saved yet." });

  const e = r.explanations;
  if (e.status === "saved") {
    out.push({
      tone: e.missing > 0 ? "warn" : "info",
      text: `Explained ${e.valid} of ${e.requested} requested${e.missing > 0 ? `; ${e.missing} missing` : ""}.${e.remaining > 0 ? ` ${e.remaining} mistake${e.remaining === 1 ? "" : "s"} still unexplained — use “Explain more”.` : ""}`,
    });
  } else if (e.status === "skipped_busy") out.push({ tone: "info", text: "Explanations are being generated by another request, so this one included only the overview." });
  else if (e.status === "none_usable" && e.requested > 0) out.push({ tone: "warn", text: `None of the ${e.requested} requested explanations was usable; nothing was saved and earlier explanations are unchanged.` });
  else if (e.status === "not_saved") out.push({ tone: "warn", text: `${e.valid} new explanation${e.valid === 1 ? " is" : "s are"} shown but not saved yet.` });
  else if (e.status === "reused" && r.action === "explain") out.push({ tone: "info", text: "Those mistakes already have saved explanations — no AI request was used." });
  else if (e.status === "conflict" || e.status === "rejected") out.push({ tone: "warn", text: "The new explanations couldn't be stored." });
  if (r.truncated) out.push({ tone: "warn", text: "The AI response was cut off at its length limit, so coverage is incomplete." });
  return out;
}

export function useAiAssessment(opts: { userId: string; roundId: string; generating: boolean }) {
  const { userId, roundId } = opts;
  const queryClient = useQueryClient();
  const scope = `${userId}:${roundId}`;
  const scopeRef = useRef(scope);
  scopeRef.current = scope;
  const alive = useRef(true);
  const controllers = useRef(new Set<AbortController>());
  useEffect(() => {
    alive.current = true;
    const set = controllers.current;
    return () => {
      alive.current = false;
      set.forEach((c) => c.abort());
      set.clear();
    };
  }, []);

  const [pending, setPending] = useState<PendingRecovery[]>(() => loadPending(userId, roundId));
  const [unsavedNotes, setUnsavedNotes] = useState<Record<string, UnsavedNoteView>>({});
  const [unsavedOverview, setUnsavedOverview] = useState<AiActionResponse["overview"] | null>(null);
  const [busy, setBusy] = useState<null | "generate" | "explain" | "save">(null);
  const [messages, setMessages] = useState<AiMessage[]>([]);
  const [storageWarning, setStorageWarning] = useState(false);
  const [quota, setQuota] = useState<QuotaView | null>(null);
  const [pollUntilDone, setPollUntilDone] = useState(false);

  const request = useCallback(
    async (url: string, body: unknown): Promise<{ ok: boolean; status: number; json: unknown } | null> => {
      const sentFor = scopeRef.current;
      const controller = new AbortController();
      controllers.current.add(controller);
      try {
        const res = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body), signal: controller.signal });
        const json = await res.json().catch(() => ({}));
        // Stale response (unmounted, or the account/round changed): ignore it.
        if (!alive.current || scopeRef.current !== sentFor) return null;
        return { ok: res.ok, status: res.status, json };
      } catch {
        if (!alive.current || scopeRef.current !== sentFor) return null;
        return { ok: false, status: 0, json: { error: "Network error — nothing was saved by this attempt." } };
      } finally {
        controllers.current.delete(controller);
      }
    },
    []
  );

  const refreshReport = useCallback(() => queryClient.invalidateQueries({ queryKey: roundReportKeys.report(userId, roundId) }), [queryClient, userId, roundId]);

  const refreshQuota = useCallback(() => {
    void fetch("/api/ai/quota")
      .then((r) => (r.ok ? (r.json() as Promise<QuotaView>) : null))
      .then((q) => {
        if (alive.current) setQuota(q);
      })
      .catch(() => {});
  }, []);
  useEffect(() => refreshQuota(), [refreshQuota]);

  /** Saves pending entries through the recover route (never the provider). */
  const recover = useCallback(
    async (items: PendingRecovery[]) => {
      if (items.length === 0) return;
      setBusy("save");
      const r = await request(`/api/session/${encodeURIComponent(roundId)}/assessment/recover`, { entries: items.map((p) => p.entry) });
      if (!r) return;
      setBusy(null);
      if (!r.ok) {
        setMessages([{ tone: "error", text: (r.json as { error?: string }).error ?? "Saving failed. Your result is still kept here — try Save again." }]);
        return;
      }
      const results = (r.json as AiRecoverResponse).results ?? [];
      const out: AiMessage[] = [];
      let anySaved = false;
      results.forEach((res, i) => {
        const item = items[i];
        if (!item) return;
        if (res.status === "not_saved") {
          out.push({ tone: "warn", text: `${item.entry.op === "overview" ? "Assessment" : "Explanations"}: still not saved — try Save again.` });
          return;
        }
        // Terminal: clear it and say what happened.
        removePending(item.key);
        setPending((prev) => prev.filter((p) => p.key !== item.key));
        if (item.entry.op === "overview") setUnsavedOverview(null);
        else setUnsavedNotes({});
        const what = item.entry.op === "overview" ? "Assessment" : "Explanations";
        if (res.status === "saved") {
          anySaved = true;
          out.push({ tone: "info", text: `${what} saved.` });
        } else if (res.status === "superseded") out.push({ tone: "warn", text: `${what}: a newer result was started, so this one was discarded.` });
        else if (res.status === "conflict") out.push({ tone: "warn", text: `${what}: a different result was already saved and was kept.` });
        else if (res.status === "expired") out.push({ tone: "warn", text: `${what}: too late to save (over 24 hours). The AI request was already used.` });
        else out.push({ tone: "warn", text: `${what}: couldn't be saved (${res.status}).` });
      });
      setMessages(out);
      if (anySaved) void refreshReport();
    },
    [request, roundId, refreshReport]
  );

  // Entries left from an earlier visit (e.g. reload): one automatic retry.
  const autoRetried = useRef(false);
  useEffect(() => {
    if (autoRetried.current || pending.length === 0) return;
    autoRetried.current = true;
    const t = setTimeout(() => void recover(pending), AUTO_RETRY_DELAY_MS);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleAction = useCallback(
    (r: AiActionResponse) => {
      const toKeep: AiRecoveryEntry[] = [];
      if (r.overview.status === "not_saved" && r.overview.recovery) {
        toKeep.push(r.overview.recovery);
        setUnsavedOverview(r.overview);
      }
      if (r.explanations.status === "not_saved" && r.explanations.recovery) {
        toKeep.push(r.explanations.recovery);
        setUnsavedNotes(Object.fromEntries((r.explanations.unsaved ?? []).map((n) => [n.attemptId, n])));
      }
      setMessages(describeAction(r));
      if (r.overview.status === "saved" || r.explanations.status === "saved") void refreshReport();
      if (toKeep.length > 0) {
        const kept = toKeep.map((entry) => ({ entry, stored: savePending(userId, roundId, entry) }));
        if (kept.some((k) => !k.stored)) setStorageWarning(true);
        const items = kept.map(({ entry }) => ({ key: recoveryKey(userId, roundId, entry), entry, savedAt: new Date().toISOString() }));
        setPending((prev) => [...prev.filter((p) => !items.some((i) => i.key === p.key)), ...items]);
        // One automatic retry of the save (no provider call).
        setTimeout(() => {
          if (alive.current) void recover(items);
        }, AUTO_RETRY_DELAY_MS);
      }
    },
    [refreshReport, recover, userId, roundId]
  );

  const run = useCallback(
    async (kind: "generate" | "explain", url: string, body: unknown) => {
      setBusy(kind);
      setMessages([]);
      const r = await request(url, body);
      if (!r) return;
      setBusy(null);
      refreshQuota();
      if (r.ok) {
        handleAction(r.json as AiActionResponse);
        return;
      }
      const err = r.json as { error?: string; code?: string };
      if (err.code === "in_progress") {
        setMessages([{ tone: "info", text: err.error ?? "Already being generated." }]);
        setPollUntilDone(true);
        return;
      }
      setMessages([{ tone: "error", text: err.error ?? "The AI request failed. Saved results are unchanged." }]);
    },
    [request, refreshQuota, handleAction]
  );

  const generate = useCallback(() => run("generate", `/api/session/${encodeURIComponent(roundId)}/assessment`, { action: "generate" }), [run, roundId]);
  const explainMore = useCallback(() => run("explain", `/api/session/${encodeURIComponent(roundId)}/explanations`, { intent: "missing" }), [run, roundId]);
  const reexplain = useCallback(
    (sentences: number[]) => run("explain", `/api/session/${encodeURIComponent(roundId)}/explanations`, { intent: "reexplain", sentences }),
    [run, roundId]
  );
  const saveNow = useCallback(() => recover(pending), [recover, pending]);

  // Bounded, read-only polling while a generation runs (the report says so,
  // or another tab's request answered in_progress). Never re-posts.
  const generating = opts.generating;
  useEffect(() => {
    if (!generating && !pollUntilDone) return;
    let count = 0;
    let timer: ReturnType<typeof setTimeout> | undefined;
    let stopped = false;
    const tick = () => {
      if (stopped || !alive.current) return;
      count++;
      void refreshReport();
      if (count < POLL_MAX) timer = setTimeout(tick, POLL_MS);
      else setPollUntilDone(false);
    };
    timer = setTimeout(tick, POLL_MS);
    return () => {
      stopped = true;
      if (timer) clearTimeout(timer);
    };
  }, [generating, pollUntilDone, refreshReport]);
  useEffect(() => {
    if (!generating && pollUntilDone) {
      // The report says nothing is running any more.
      const t = setTimeout(() => setPollUntilDone(false), POLL_MS * 2);
      return () => clearTimeout(t);
    }
  }, [generating, pollUntilDone]);

  return {
    busy,
    messages,
    quota,
    pending,
    unsavedNotes,
    unsavedOverview,
    storageWarning,
    polling: generating || pollUntilDone,
    generate,
    explainMore,
    reexplain,
    saveNow,
  };
}
