-- Persists the structured AI "session assessment" (verdict/strengths/
-- weaknesses/recommendation) generated by /api/session/[sessionId]/explain-all,
-- so it survives a page reload or a later visit to the session's report
-- instead of only living in React state for that one browser session.

alter table learning_sessions add column if not exists ai_assessment jsonb;
alter table learning_sessions add column if not exists ai_assessment_generated_at timestamptz;
