-- Adds canonical-form/learning-pattern metadata to saved vocabulary items.
-- Purely additive: nullable columns, no default beyond NULL, no backfill.
-- Existing rows read back with both columns null and render exactly as
-- before (title falls back to `term`, no Pattern block shown).
--
-- Populated by the deterministic vocab-highlight pipeline
-- (src/lib/vocabHighlights) when a saved item was captured from a
-- recognized highlight — e.g. canonical_form = 'give up' for a saved
-- surface term of 'given up'. Never generated by this migration or by any
-- read path; write-time only, via POST/PATCH /api/vocabulary.
alter table vocabulary_items
  add column canonical_form text null,
  add column learning_pattern text null;
