-- Adds a pronunciation-audio URL to saved vocabulary items. Purely
-- additive: a nullable column, no default beyond NULL, no backfill.
-- Existing rows read back with audio_url null and simply show no
-- pronunciation control.
--
-- Sourced from the free dictionary API's phonetics[].audio field (see
-- lookupWordDetails in src/lib/dictionary.ts) — the same lookup that already
-- supplies phonetic/part_of_speech/definition, so this is not a new
-- third-party integration, just persisting a field that lookup already
-- fetched and previously discarded. Single words only: the free dictionary
-- API (and therefore this column) never applies to multi-word phrases.
-- Write-time only, via POST /api/vocabulary; never generated by this
-- migration or by any read path.
alter table vocabulary_items
  add column audio_url text null;
