import { PIPELINE_VERSION, LEGACY_GEMINI_PIPELINE_VERSION } from "@/lib/vocabHighlights/config";
import { readCachedHighlights } from "@/lib/vocabHighlights/cache";
import type { SupabaseClient } from "@supabase/supabase-js";

// The construction-expansion/boundary-validation/hyphen-compound/NER-for-MWE
// changes in this pass alter candidate generation, scoring, and overlap
// behavior — any highlight row cached under the PREVIOUS pipeline version
// was generated by the old rules and must never be served again. Bumping
// PIPELINE_VERSION (not a new DB migration) is what invalidates it, since
// cache reads/writes key on this string — see cache.ts.
describe("pipeline version bump invalidates old rows", () => {
  it("PIPELINE_VERSION was bumped for this change (not left equal to any previous release's value)", () => {
    // Every version string this pipeline has ever shipped under — a new
    // release must never reuse one of these, or a stale cache row would be
    // served as if it were current.
    expect(PIPELINE_VERSION).not.toBe("vocab-pipeline-v1");
    expect(PIPELINE_VERSION).not.toBe("vocab-pipeline-v2");
    expect(PIPELINE_VERSION).not.toBe("vocab-pipeline-v3");
    expect(PIPELINE_VERSION).not.toBe(LEGACY_GEMINI_PIPELINE_VERSION);
  });

  it("a row cached under the previous pipeline version is never returned for the current one", async () => {
    const builder: Record<string, jest.Mock> = {};
    const chain = () => builder;
    builder.select = jest.fn(chain);
    let eqCallCount = 0;
    const capturedEq: unknown[][] = [];
    builder.eq = jest.fn((...args: unknown[]) => {
      capturedEq.push(args);
      eqCallCount++;
      if (eqCallCount >= 3) {
        return Promise.resolve({
          data: [
            {
              segment_index: 0,
              phrases: [{ phrase: "paired", translation: null, start: 0, end: 6 }],
              status: "complete",
              transcript_text_hash: "hash-0",
              azure_used: false,
            },
          ],
          error: null,
        });
      }
      return builder;
    });
    const supabase = { from: jest.fn(() => builder) } as unknown as SupabaseClient;

    // The query itself filters by pipeline_version server-side (verified by
    // the 3rd .eq() call being pipeline_version) — a row from
    // "vocab-pipeline-v1" would never even be returned by this query when
    // called with the current PIPELINE_VERSION, since Supabase's .eq()
    // filters server-side. This test documents that contract at the
    // application layer: readCachedHighlights always passes the CURRENT
    // PIPELINE_VERSION as its filter, never a stale one.
    await readCachedHighlights(supabase, "t1", "B1", PIPELINE_VERSION, new Map([[0, "hash-0"]]));
    expect(capturedEq[2]).toEqual(["pipeline_version", PIPELINE_VERSION]);
    expect(capturedEq[2][1]).not.toBe("vocab-pipeline-v1");
  });
});
